PART_OF_MAP_WIDTH, PART_OF_MAP_HEIGHT = 200, 200
INFO_SIZE = INFO_WIDTH, INFO_HEIGHT = round(PART_OF_MAP_HEIGHT * 0.2), round(PART_OF_MAP_HEIGHT * 0.2)
ICON_SIZE = ICON_WIDTH, ICON_HEIGHT = round(PART_OF_MAP_HEIGHT * 0.3), round(PART_OF_MAP_HEIGHT * 0.3)
AMOUNT_OF_PARTS_IN_ROW, AMOUNT_OF_PARTS_IN_COL = 20, 16
SIZE = WIDTH, HEIGHT = PART_OF_MAP_WIDTH * AMOUNT_OF_PARTS_IN_ROW, PART_OF_MAP_HEIGHT * AMOUNT_OF_PARTS_IN_COL

SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1250, 680
WARRIOR_WIDTH = SCREEN_WIDTH // 10
WARRIOR_HEIGHT = SCREEN_HEIGHT // 5

WARRIOR_HEALTH_POSITION = (round(SCREEN_WIDTH * 0.9), round(SCREEN_HEIGHT * 0.015))
WARRIOR_POWER_POSITION = (round(SCREEN_WIDTH * 0.9), round(SCREEN_HEIGHT * 0.1))
WARRIOR_TIME_POSITION = (round(SCREEN_WIDTH * 0.9), round(SCREEN_HEIGHT * 0.18))
WARRIOR_INFO_DELTA = round(SCREEN_WIDTH * 0.05)

WALKING_SPEED = 4
RUNNING_SPEED = 8

JUMPING_COUNT = 18
JUMPING_K = 0.2
FALLING_ACCELERATION = 2

MODE_IMPORTANCE = {
    'collect': 0,
    'idle': 1,
    'walk': 2,
    'run': 3,
    'fall': 4,
    'jump': 4,
    'hurt': 5,
    'attack': 6,
    'die': 7
}

FPS = 30

BACKGROUND_NAME = 'background_block.png'
GROUND_GRASS_BLOCK_NAME = 'ground_grass.png'
PINK_GROUND_BLOCK_NAME = 'pink_ground.png'
WOODEN_BOX_BLOCK_NAME = 'wooden_box.png'
WALL_BLOCK_NAME = 'wall.png'
HEALTH_ICON_NAME = 'health.png'
POWER_ICON_NAME = 'power.png'
TIME_ICON_NAME = 'time.png'
POTION_ICON_NAME = 'potion.png'
SHIELD_ICON_NAME = 'shield.png'
APPLE_ICON_NAME = 'apple.png'

SCHEMA_LETTER_TO_BLOCK = {
    '.': BACKGROUND_NAME,
    'G': GROUND_GRASS_BLOCK_NAME,
    'P': PINK_GROUND_BLOCK_NAME,
    'U': WOODEN_BOX_BLOCK_NAME,
    'W': WALL_BLOCK_NAME,
    'T': POWER_ICON_NAME,
    'S': SHIELD_ICON_NAME,
    'A': APPLE_ICON_NAME
}

RED = (255, 0, 0)
BLUE = (67, 170, 255)
GRAY = (197, 208, 230)
