PART_OF_MAP_WIDTH, PART_OF_MAP_HEIGHT = 200, 200
AMOUNT_OF_PARTS_IN_ROW, AMOUNT_OF_PARTS_IN_COL = 20, 7
SIZE = WIDTH, HEIGHT = PART_OF_MAP_WIDTH * AMOUNT_OF_PARTS_IN_ROW, PART_OF_MAP_HEIGHT * AMOUNT_OF_PARTS_IN_COL

SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1250, 680
WARRIOR_WIDTH = SCREEN_WIDTH // 10
WARRIOR_HEIGHT = SCREEN_HEIGHT // 5

WALKING_SPEED = 4
RUNNING_SPEED = 8

JUMPING_COUNT = 18
JUMPING_K = 0.2
FALLING_ACCELERATION = 5

MODE_IMPORTANCE = {
    'idle': 1,
    'walk': 2,
    'run': 3,
#    'fall': 4,
    'jump': 4,
    'hurt': 5,
    'attack': 6,
    'die': 7
}

FPS = 30

BACKGROUND_NAME = 'background_block.png'
GROUND_GRASS_BLOCK_NAME = 'ground_grass.png'
PINK_GROUND_BLOCK_NAME = 'pink_ground.png'
WOODEN_BOX_BLOCK_NAME = 'wooden_box.png'
WALL_BLOCK_NAME = 'wall.png'

SCHEMA_LETTER_TO_BLOCK = {
    '.': BACKGROUND_NAME,
    'G': GROUND_GRASS_BLOCK_NAME,
    'P': PINK_GROUND_BLOCK_NAME,
    'U': WOODEN_BOX_BLOCK_NAME,
    'W': WALL_BLOCK_NAME
}

