PART_OF_MAP_WIDTH, PART_OF_MAP_HEIGHT = 200, 200
AMOUNT_OF_PARTS_IN_ROW, AMOUNT_OF_PARTS_IN_COL = 20, 6
SIZE = WIDTH, HEIGHT = PART_OF_MAP_WIDTH * AMOUNT_OF_PARTS_IN_ROW, PART_OF_MAP_HEIGHT * AMOUNT_OF_PARTS_IN_COL

SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1250, 680
WARRIOR_WIDTH = SCREEN_WIDTH // 10
WARRIOR_HEIGHT = SCREEN_HEIGHT // 5

WALKING_SPEED = 4
RUNNING_SPEED = 8
JUMPING_COUNT = 14
JUMPING_K = 0.3

MODE_IMPORTANCE = {
    'idle': 1,
    'walk': 2,
    'run': 3,
    'jump': 4,
    'hurt': 5,
    'attack': 6,
    'die': 7
}

FPS = 20
BACKGROUND_NAME = 'Brown.png'
