LEVELS = {
    1: ['WWWWWWWWWWWWWWWWWWWW',
        'W..................W',
        'W.P..UU...G...G....W',
        'W...............P..W',
        'W....PP....U..T....W',
        'W....A........GG...W',
        'W....U.....S.......W',
        'W.........TP...S...W',
        'W..A......G....UU..W',
        'W.GG....P.....U....W',
        'W....T.....A...A...W',
        'W....UU...GG...P.S.W',
        'WP..T.U.A....S...G.W',
        'W...UUU.U....G....PW',
        'W...............P..W',
        'WWWWWWWWWWWWWWWWWWWW'],
    2: ['WWWWWWWWWWWWWWWWWWWW',
        'W..................W',
        'W....UU.......G....W',
        'WPP......PP.....P..W',
        'W....P..A..U.......W',
        'W..PPPPPPP..A.G....W',
        'W...........P......W',
        'W.U...P....P.......W',
        'W....PPP.....S.UU..W',
        'W.GG....PGG.GUU....W',
        'W..S....A.......A..W',
        'W....UU...GGG..P...W',
        'WP.P...U.AA..P...G.W',
        'W...UUU......G....PW',
        'W...............P..W',
        'WWWWWWWWWWWWWWWWWWWW']
}
