from .size_configurations import SCREEN_WIDTH, SCREEN_HEIGHT

WARRIOR_INFO_POSITION = (round(SCREEN_WIDTH * 0.9), round(SCREEN_HEIGHT * 0.015))
WARRIOR_INFO_DELTA_X = round(SCREEN_WIDTH * 0.05)
WARRIOR_INFO_DELTA_Y = round(SCREEN_HEIGHT * 0.1)