from .size_configurations import SCREEN_WIDTH, SCREEN_HEIGHT

WARRIOR_HEALTH_POSITION = (round(SCREEN_WIDTH * 0.9), round(SCREEN_HEIGHT * 0.015))
WARRIOR_POWER_POSITION = (round(SCREEN_WIDTH * 0.9), round(SCREEN_HEIGHT * 0.1))
WARRIOR_TIME_POSITION = (round(SCREEN_WIDTH * 0.9), round(SCREEN_HEIGHT * 0.18))
WARRIOR_INFO_DELTA = round(SCREEN_WIDTH * 0.05)